name: simple_bloc_weather_app
description: "A Simple weather app using bloc"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.2.1
  http: ^0.13.4
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading.gif
    - .env

